### PR TITLE
Update v3.28.0

### PR DESCRIPTION
**Pull request by LeandroStanger**

### CODE REVIEW

**Comment by jurf** [comment]
Why not 3.26.2?

**Comment by TingPing** [comment]
I think @csoriano1618 said he might just want to remove Nautilus from flathub anyway as its less generally useful and was more of an experiment?

**Comment by csoriano1618** [comment]
TingPing: We are working now on a modified version for stable, to make sure people are aware it's the Flatpak one and to make it available alongside the system one. Then I'll be comfortable having it in FlatHub

**Comment by barthalion** [comment]
Fair enough, but it doesn't build: https://flathub.org/builds/#/builders/2/builds/210

**Comment by csoriano1618** [comment]
Whops, I assumed it was tested...

**Comment by csoriano1618** [comment]
Anyway, this work I was mentioning before is for tomorrow, so I'll have a working update.

**Comment by csoriano1618** [comment]
Updated, should work now.

**Pull request merged**
